name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore SnaPDataTransfer.sln
  
    - name: Setup HTTPS certificate
      run: sudo apt-get install -y libnss3-tools
           dotnet dev-certs https
           sudo -E dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM
           certutil -d sql:$HOME/.pki/nssdb -A -t "P,," -n localhost -i /usr/local/share/ca-certificates/aspnet/https.crt
           certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n localhost -i /usr/local/share/ca-certificates/aspnet/https.crt
           
    - name: Build
      run: dotnet build SnaPDataTransfer.sln --no-restore
      
    - name: Test
      run: dotnet test SDT.Tests/SDT.Tests.csproj --no-build --verbosity normal
